RestSharpEx/Controllers/WeatherController.cs
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using RestSharpEx.Models;

namespace RestSharpEx.Controllers
{
    public class WeatherController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult QueryWeatherApi(string city)
        {
            string apiEndPoint = HttpContext.Request.Url.GetLeftPart(UriPartial.Authority);

            var client = new RestClient(apiEndPoint);
            var request = new RestRequest("/api/WeatherApi", Method.GET);

            request.AddParameter("city", city);

            request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };

            var response = client.Execute<WeatherDataModel>(request);

            WeatherDataModel model = response.Data;

            return View(model);
        }
    }
}

RestSharpEx/Views/Weather/Index.cshtml
@{
    ViewBag.Title = "View";
}

<div class="container">
    <h2>Weather API</h2>

    @using (Html.BeginForm("QueryWeatherApi", "Weather", FormMethod.Post))
    {
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                <input type="text" id="city" name="city" placeholder="Search weather by city" class="form-control" />
            </div>
        </div>
    }
</div>

RestSharpEx/Views/Weather/QueryWeatherApi.cshtml
@model RestSharpEx.Models.WeatherDataModel
@{
    ViewBag.Title = "QueryWeatherApi";
}

<h2>Current Weather Details of @Model.name.ToUpper()</h2>
<br />
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>City</th>
        <th>Weather</th>
        <th>Temperature</th>
        <th>Temperature Max</th>
        <th>Temperature Min</th>
        <th>Pressure</th>
        <th>Humidity</th>
        <th>OpenWeather ID</th>
    </tr>
    <tr>
        <td>@Model.name</td>
        <td>@Model.weather[0].main</td>
        <td>@Model.main.temp</td>
        <td>@Model.main.temp_max</td>
        <td>@Model.main.temp_min</td>
        <td>@Model.main.pressure</td>
        <td>@Model.main.humidity</td>
        <td>@Model.id</td>
    </tr>
</table>